---
exclude: |
  (?x)^(
    files/.bashrc.d/git-flow-completion.bash|
    files/.bashrc.d/git-prompt.sh|
    files/.bashrc.d/git-completion.bash|
    files/.bashrc.d/zz-alias-completion.bash|
    files/.bin/AM-INSTALLER
  )$
repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.1 # or other specific tag
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-encoding-pragma
        args: [--remove]
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args: [-i 4, -ci, -bn]
      - id: shellcheck
        args: [-x]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [-w, '120']
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
