#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
if [[ $EUID -eq 0 ]]; then
    echo "This script must NOT be run as root" 1>&2
    exit 1
fi
cd "$(dirname "$0")" || exit
here=$(pwd)
. lib/traceback.sh
## predefined functions

realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

retry_root() {
    if ! command -v "$1"; then
        echo "$1 not existed!"
        exit 1
    fi
    cmd=$(command -v "$1")
    shift
    if ! $cmd "$@"; then
        sudo -H LANG=C "$cmd" "$@"
    fi
}

# setup env and location
source files/.bashrc.d/get-platform
source /etc/lsb-release

function install_pkg() {
    if ! _install_pkg "$@"; then
        update_pkg_list
        _install_pkg "$@"
    fi
}
case $platform in
    'linux')
        check_pkg() { dpkg -s "$1" >/dev/null 2>&1; }
        # aptitude can solve depenency problem for clang-*
        _install_pkg() { sudo apt-get install -y "$@"; }
        update_pkg_list() { sudo apt-get update; }
        # setup aptitude first
        install_pkg aptitude
        _install_pkg() { sudo aptitude install -y "$@"; }
        ;;
    'mac')
        check_pkg() { brew list -1 | grep -q "^${1}\$"; }
        _install_pkg() { brew install "$@"; }
        update_pkg_list() { :; }
        if ! brew help >/dev/null; then
            ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        fi
        ;;
esac

#######################
## install packages on new machine
#######################

packages=(git dos2unix wget curl)

case $platform in
    'linux')
        sudo snap install lnav
        # test if /etc/apt/sources.list.d/git-core-ubuntu-ppa-*.list existed
        files=(/etc/apt/sources.list.d/git-core-ubuntu-ppa-*.list)
        if [[ ! -f "${files[0]}" ]]; then
            sudo add-apt-repository -y ppa:git-core/ppa
        fi
        packages+=(sshfs)             # fs
        packages+=(sshpass)           # fs
        packages+=(cifs-utils)        # fs
        packages+=(plocate)           # fs: search
        packages+=(silversearcher-ag) # fs: search
        packages+=(jq)                # shell tool
        packages+=(moreutils)         # shell tool: sponge
        packages+=(apt-file)          # sysadmin
        packages+=(bmon)              # sysadmin
        packages+=(ncdu)              # sysadmin
        packages+=(build-essential)   # dev: build tool
        packages+=(vim)               # dev: build tool
        packages+=(meld tig)          # dev: SVC tools
        packages+=(direnv)            # dev: env control
        packages+=(exuberant-ctags)   # dev: Coding tools
        packages+=(unzip)
        packages+=(manpages-dev manpages-posix-dev)
        packages+=(cmake)      # vim YouCompleteMe
        packages+=(shellcheck) # for vim syntastic
        packages+=(fonts-firacode)
        packages+=(powerline)
        packages+=(powerline-gitstatus)
        ;;
    'mac')
        packages+=(ctags)
        packages+=(python)
        packages+=(coreutils)
        ;;
esac
install_pkg "${packages[@]}"
packages=()

#######################
## install pyenv
#######################
if [[ ! -d ~/.pyenv ]]; then
    curl https://pyenv.run | bash
else
    (
        cd ~/.pyenv || exit
        git pull --rebase
    )
fi

if command -v pyenv; then
    pyenv rehash
fi

pyenv global 3

# install user venv (include ansible)
python3 -m venv ~/venv
# shellcheck source=/dev/null
source ~/venv/bin/activate
pip install -I -U -r requirements_dotfiles.txt

#
# Use ansible
#
ansible-playbook -i "localhost," -c local site.yml

#######################
## Backup dotfiles and replace with link
#######################

find -L ~ -maxdepth 1 -type l -delete
(
    unset GREP_OPTIONS
    if [[ -d ~/.config && ! -L ~/.config ]]; then
        rm -rvf ~/.config
    fi
    find "$here/files/" -maxdepth 1 -mindepth 1 | while read -r src; do
        if [[ "$(realpath "$HOME/${src##*/}")" -ef "$src" ]]; then
            echo "$HOME/${src##*/}" is ready
        else
            ln -sv "$src" ~/
        fi
    done
)

#######################
## install vim plugins
#######################
mkdir -p ~/.backup vim/autoload
curl -fLo vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +qa
find "$HOME/.vim/" -name \*.vim -exec dos2unix -q {} \;

#######################
## install tmux plugins
#######################
if [[ ! -d ~/.tmux/plugins/tpm ]]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
    (
        cd ~/.tmux/plugins/tpm || exit
        git pull --rebase
    )
fi

#######################
## Local changes
#######################
# Setup self default using rebase when pull
git config branch.master.rebase true

# patch fonts for powerline
[ "$1" = "x" ] && get fontconfig && fc-cache -vf ~/.fonts

# Daily Update dotfiles repo
if ! (crontab -l | grep -q git_update_dotfiles.bash); then
    crontab -l \
        | {
            cat
            echo "@daily $here/git_update_dotfiles.bash"
        } \
        | crontab -
fi

#######################
## Local fixes
#######################
rm -rf "$here/local"
if [[ -L ~/.local ]]; then
    rm ~/.local
fi

gsettings set org.gnome.desktop.wm.preferences focus-new-windows 'smart'
