- hosts: all
  become: True
  tasks:
# SUDO
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
    
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add sudoers users to wheel group
      user:
        name={{ lookup('env', 'USER') }}
        groups=wheel
        append=yes
        state=present
        createhome=yes

    - name: Cleanup old sudoers config
      file:
        state=absent
        path='/etc/sudoers.d/50_{{ lookup('env', 'USER') }}_sh'

# UseDNS no
    - name: Update the /etc/ssh/sshd_config file
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^UseDNS"
        line: "UseDNS no"
        insertafter: EOF
        state: present
      register: ssh_config

    - name: Restart ssh
      service:
        name: ssh
        state: restarted
      when: ssh_config.changed

## Delete dead links
    - name: Delete dead links
      command: find -L {{ lookup('env','HOME') }} -maxdepth 1 -type l -print -delete
      register: command_result
      changed_when: "command_result.stdout != ''"
# vim:ft=ansible:
