#!/usr/bin/env ruby

require 'net/http'
require 'uri'
require 'json'

if `git branch --list`.include? "no branch, rebasing"
  exit
end

def get_parent_pid(pid)
  stat_file = "/proc/#{pid}/stat"
  stat_content = File.read(stat_file)
  parent_pid = stat_content.split(" ")[3].to_i
  parent_pid
end

def process_ancestors_names(pid)
  parent_pid = get_parent_pid(pid)
  return false if parent_pid == 0 # Stop recursion when reaching the init process
  parent_name = `ps -o comm= -p #{parent_pid}`.strip

  if parent_name == "lazygit"
    exit
  end

  process_ancestors_names(parent_pid)
end


current_pid = Process.pid
process_ancestors_names(current_pid)

begin
  tty = open("/dev/tty", "w+")
  tty.puts "Related redmine issue: "

  input = tty.gets&.chop
  begin
    tid = Integer(input.match(%r'issues/(\d+)')&.[](1) || input)
  rescue
    puts "no input id"
    exit
  end
  line = ""
  if ENV["REDMINE_TOKEN"]
    url = "https://redmine.teamt5.net/issues/#{tid}"
    uri = URI.parse("#{url}.json")
    request = Net::HTTP::Get.new(uri)
    request.content_type = "application/json"
    request["X-Redmine-Api-Key"] = ENV["REDMINE_TOKEN"]
    req_options = { use_ssl: uri.scheme == "https" }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
      http.request(request)
    end
    data = JSON.parse(response.body)
    line = "\n\n[#{data['issue']['tracker']['name']} ##{data['issue']['id']} #{data['issue']['subject']}](#{url})"
  else
    commentchar=`git config --get core.commentchar`.strip
    line = "\n\nhttps://redmine.teamt5.net/issues/#{tid} ##{tid}\n#{commentchar}prepare-commit-msg: set REDMINE_TOKEN to get full issue title"
  end

  original_file = ARGV[0]
  new_file = original_file + '.new'
  File.open(new_file, 'w') do |fo|
    fo.puts line
    File.foreach(original_file) do |li|
      fo.puts li
    end
  end
  File.rename(new_file, original_file)


rescue
end
