#!/bin/bash
#-------------------------------------------------------------
# customize PATH
#-------------------------------------------------------------
path_list=(
	"$HOME/.local/bin"
	"$HOME/.cargo/bin"              # rust
	"${KREW_ROOT:-$HOME/.krew}/bin" # plugin manager for kubectl
	"$HOME/bin/gam7"                # Google Apps Manager
	"$HOME/.local/share/JetBrains/Toolbox/apps"
	/usr/local/go/bin
	/usr/local/bin
)
for path in "${path_list[@]}"; do
	if [[ -d "$path" ]]; then
		PATH_append "$path"
	fi
done
