#!/bin/bash
#-------------------------------------------------------------
# customize PATH
#-------------------------------------------------------------

PATH_prepend /usr/sbin

PATH_append "$HOME/.bin"
PATH_append "$HOME/.local/bin"
PATH_append "$HOME/.local/share/mise/shims"
PATH_append "$HOME/.cargo/bin"              # rust
PATH_append "${KREW_ROOT:-$HOME/.krew}/bin" # plugin manager for kubectl
PATH_append "$HOME/bin/gamadv-xtd3"         # Google Apps Manager
PATH_append "$HOME/.local/share/JetBrains/Toolbox/apps"
PATH_append /usr/local/go/bin
PATH_append /usr/local/bin
