#!/bin/bash

eval "$(mise hook-env -s bash)"
# shellcheck disable=SC2154
if [[ $(who am i) =~ \([0-9a-z.\-]+\)$ || "$platform" == "mac" || "$platform" == "linux" || "$TMUX" != "" || "$SUDO_USER" != "" ]]; then
	PATH="$PATH:$(python -c "import sysconfig; print(sysconfig.get_path('scripts'))")"
	mapfile -t sites < <(python -c 'import site; print(" ".join(site.getsitepackages()))')
	sites=(/usr/share "${sites[@]}")
	for site in "${sites[@]}"; do
		powerline="$site/powerline/bindings/bash/powerline.sh"
		if [ -f "$powerline" ]; then
			echo "Powerline found at $powerline"
			powerline-daemon -q || true
			# shellcheck disable=SC2034
			POWERLINE_BASH_CONTINUATION=1
			# shellcheck disable=SC2034
			POWERLINE_BASH_SELECT=1
			# shellcheck source=/dev/null
			source "$powerline"
			break
		else
			echo "No powerline at $powerline"
		fi
	done
fi
# append a command at the last line, inside curly brackets  of function _powerline_prompt
patch_function _powerline_prompt 'echo -n " "'
unset srcfiles powerline
