#!/bin/bash
PATH="$(echo -e "${PATH//:/\\n}" | awk '!x[$0]++' | grep -v '^$' | paste -sd ":" -)"
removepath() {
    local path="$1"
    PATH="$(echo -e "${PATH//:/\\n}" | grep -v "$path" | paste -sd ":" -)"
    export PATH
}

