#!/usr/bin/env ruby

require 'net/http'
require 'uri'
require 'json'

if `git branch --list`.include? "no branch, rebasing"
  exit
end

begin
  tty = open("/dev/tty", "w+")
  tty.puts "Related redmine issue: "

  input = tty.gets&.chop
  begin
    tid = Integer(input.match(%r'issues/(\d+)')&.[](1) || input) 
  rescue
    puts "no input id"
    exit
  end
  line = ""
  if ENV["REDMINE_TOKEN"]
    url = "https://redmine.teamt5.net/issues/#{tid}"
    uri = URI.parse("#{url}.json")
    request = Net::HTTP::Get.new(uri)
    request.content_type = "application/json"
    request["X-Redmine-Api-Key"] = ENV["REDMINE_TOKEN"]
    req_options = { use_ssl: uri.scheme == "https" }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
      http.request(request)
    end
    data = JSON.parse(response.body)
    line = "\n\n[#{data['issue']['tracker']['name']} ##{data['issue']['id']} #{data['issue']['subject']}](#{url})"
  else
    commentchar=`git config --get core.commentchar`.strip
    line = "\n\nhttps://redmine.teamt5.net/issues/#{tid} ##{tid}\n#{commentchar}prepare-commit-msg: set REDMINE_TOKEN to get full issue title"
  end

  File.open(ARGV[0], "a") do |f|
    f.puts line
  end

end
