#!/bin/bash
#===============================================================
#
# ALIASES AND FUNCTIONS
#
# Arguably, some functions defined here are quite big.
# If you want to make this file smaller, these functions can
# be converted into scripts and removed from here.
#
# Many functions were taken (almost) straight from the bash-2.04
# examples.
#
#===============================================================

#-------------------
# Personnal Aliases
#-------------------

alias ssh='export LC_ALL=en_US.UTF-8; ssh'
alias aa='vim ~/.bashrc && source ~/.bashrc'
alias as='vim ~/.bashrc.d/bash_aliases && source ~/.bashrc'
alias an='source ~/.bashrc'
alias zz='vim ~/.vimrc'

alias wttr='curl "wttr.in/taipei?1p&lang=zh"'
alias rm='rm -ri'
alias cp='cp -ri'
alias mv='mv -i'
# -> Prevents accidentally clobbering files.
alias mkdir='mkdir -p'
alias grep='grep --color=auto --binary-files=without-match'

alias h='history'
alias j='jobs -l'
alias which='type -a'
alias cdd='cd $(\ls -a -d .. * | percol --prompt-bottom --result-bottom-up);ls'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias path='echo -e ${PATH//:/\\n}'
alias libpath='echo -e ${LD_LIBRARY_PATH//:/\\n}'

alias du='du -kh'       # Makes a more readable output.
alias df='df -kTh'

# Commands
alias ivm='vim'
alias tmux='tmux -2 new -D -A -s main'

set_title() { printf '\e]2;%s\a' "$*"; }
alias tt='set_title'

#-------------------------------------------------------------
# The 'ls' family (this assumes you use a recent GNU ls)
#-------------------------------------------------------------
if [[ $(uname) == 'Linux' ]]; then
    alias ls='ls -h -F --color=auto'
else
    alias ls='ls -AhG'
fi
alias sl='ls'
alias l="ls -l"
alias ll="ls -l"
alias la='ls -a'          # show hidden files
alias lla='ls -la'          # show hidden files
alias lk='ls -lSr'         # sort by size, biggest last
alias lc='ls -ltcr'        # sort by and show change time, most recent last
alias lu='ls -ltur'        # sort by and show access time, most recent last
alias lt='ls -ltr'         # sort by date, most recent last
alias lm='ls -l |more'    # pipe through 'more'
alias lr='ls -lR'          # recursive ls

#-------------------------------------------------------------
# Git alias
#-------------------------------------------------------------
alias add='git add'
alias br='git branch --sort=-committerdate -vv'
alias bra='br -a'

alias ci='git commit --verbose'
alias ciam='git commit --verbose --amend'
fixup() {
    if [ -n "$1" ]; then
        git add "$1"
        git commit --amend --no-edit
        git push --force-with-lease
    fi
}
alias co='git checkout --recurse-submodules'
alias cs='git checkout $(__git_refs | percol)'
alias gd='git diff'
alias gr=$'git log --graph --pretty=format:\'%Cred%h%Creset%x09%C(yellow) %d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset\' --abbrev-commit --date=relative'
alias gra='gr --all'

alias gre='git remote'
alias st='git status'
alias gcp='git cherry-pick'
alias gcpc='git cherry-pick --continue'
alias gp='git push --force-with-lease'
alias gu='git up'
alias gm='git merge'
alias gmt='git mergetool'
alias grc='git rebase --continue || git status'
alias grs='git rebase --skip'
alias gsu='git submodule update --force --init'

alias guptag='git tag -l | xargs git tag -d && git fetch'
alias gltag='git for-each-ref refs/tags/ --format "%(objecttype) %(refname:short)" |  while read ty name; do [ $ty = commit ] && echo $name; done'
alias gva='(builtin \cd $(git rev-parse --show-toplevel); vim $(git status --porcelain | sed -ne "s#.* ##p"))'
alias gt='git tag'

touchtag(){ tag=$1; export GIT_COMMITTER_DATE="$(git show $tag --format=%aD | head -1)"; git tag -a -m $tag -f $tag $tag; }
deltag() {
    git tag -d $1
    git push -d origin $1
}
delbr() {
    git branch -D $1
    git push -d origin $1
}
mvtag() {
    git tag $2 $1
    git tag -d $1
    git push -d origin $1&
    git push origin $2&
    wait
}
mvbr() {
    git branch -m $1 $2
    git push -d origin $1&
    git push origin $2&
}
remote_tag(){ git tag -f $1 $2; git push -f origin $1; }

alias tig='tig --stat=$COLUMNS'
alias ag='ag --ignore=*~'

#-------------------------------------------------------------
# Admin assistant
#-------------------------------------------------------------
alias adu='sudo apt-get update && sudo apt-get dist-upgrade --auto-remove --purge -f -y'

#-------------------------------------------------------------
# Docker
#-------------------------------------------------------------
alias dclean='docker ps -a -q|xargs -r docker rm; docker images -q -f dangling=true|xargs -r docker rmi; docker volume ls -qf dangling=true|xargs -r docker volume rm'
alias dt='docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t'
alias dr='docker run'
alias dp='docker push'
alias dip='docker inspect --format "{{.NetworkSettings.IPAddress}}"'
alias rmi='docker rmi'
