#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
common_lib="$(dirname "$(readlink -f "$0")")/common-lib"
if [[ -f "$common_lib" ]]; then
    # shellcheck source=common-lib
    . "$common_lib"
else
    echo "Cannot find common-lib."
    exit 1
fi

if ! sudo grep -q "^$USER ALL=NOPASSWD: ALL" /etc/sudoers; then
    sudo bash -c "echo '$USER ALL=NOPASSWD: ALL' >> /etc/sudoers"
fi
