#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
. common-lib

function install_pkg() {
    if ! _install_pkg "$@"; then
        update_pkg_list
        _install_pkg "$@"
    fi
}

ubuntu_apt_update() {
    if [[ -f /etc/apt/sources.list.d/official-package-repositories.list ]]; then
        sudo sed -i -e 's/archive.ubuntu.com\|security.ubuntu.com/free.nchc.org.tw/' /etc/apt/sources.list.d/official-package-repositories.list
    fi
    if [[ -f /etc/apt/sources.list ]]; then
        sudo sed -i -e 's/archive.ubuntu.com\|security.ubuntu.com/free.nchc.org.tw/' /etc/apt/sources.list
    fi
    LOG_FILE="/var/log/apt/history.log"
    if [[ ! -f "$LOG_FILE" ]]; then
        return
    fi
    LAST_UPDATE=$(grep -m 1 "Start-Date" "$LOG_FILE" | awk '{print $2, $3}')
    if [[ -z "$LAST_UPDATE" ]]; then
        echo "未找到 apt update 的執行記錄。"
        return
    fi
    LAST_UPDATE_TIMESTAMP=$(date -d "$LAST_UPDATE" +%s)
    CURRENT_TIMESTAMP=$(date +%s)
    SECONDS_SINCE_LAST_UPDATE=$((CURRENT_TIMESTAMP - LAST_UPDATE_TIMESTAMP))
    if [[ $SECONDS_SINCE_LAST_UPDATE -gt 86400 ]]; then
        echo "已超過一天未執行 apt update。"
        sudo apt-get update
    fi
}
case $platform in
    'linux')
        check_pkg() { dpkg -s "$1" >/dev/null 2>&1; }
        # aptitude can solve depenency problem for clang-*
        _install_pkg() { sudo apt-get install -y "$@"; }
        update_pkg_list() { ubuntu_apt_update; }
        # setup aptitude first
        install_pkg aptitude
        _install_pkg() { sudo aptitude install -y "$@"; }
        ;;
    'mac')
        check_pkg() { brew list -1 | grep -q "^${1}\$"; }
        _install_pkg() { brew install "$@"; }
        update_pkg_list() { :; }
        if ! brew help >/dev/null; then
            ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        fi
        ;;
esac

#######################
## install packages on new machine
#######################

packages=(git dos2unix wget curl)

case $platform in
    'linux')
        # Add Git PPA if not already present
        if ! find /etc/apt/sources.list.d/ -name 'git-core-ubuntu-ppa-*.list'; then
            sudo add-apt-repository -y ppa:git-core/ppa
        fi

        # Define Linux-specific packages
        linux_packages=(
            # shell tools
            hstr
            # Filesystem tools
            sshfs sshpass cifs-utils plocate silversearcher-ag
            # Shell and system admin tools
            jq moreutils apt-file bmon ncdu lnav htop
            # Development tools
            build-essential vim meld tig direnv exuberant-ctags
            unzip manpages-dev manpages-posix-dev cmake shellcheck
            git-delta
            # Fonts and UI
            fonts-firacode tmux
            # GUI
            diodon xclip
        )
        packages+=("${linux_packages[@]}")
        ;;
    'mac')
        # Define macOS-specific packages
        mac_packages=(ctags python coreutils)
        packages+=("${mac_packages[@]}")
        ;;
esac

# Install all packages
install_pkg "${packages[@]}"
