#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
. common-lib

function install_pkg() {
    if ! _install_pkg "$@"; then
        update_pkg_list
        _install_pkg "$@"
    fi
}

case $platform in
    'linux')
        check_pkg() { dpkg -s "$1" >/dev/null 2>&1; }
        # aptitude can solve depenency problem for clang-*
        _install_pkg() { sudo apt-get install -q -y "$@"; }
        update_pkg_list() { ubuntu_apt_update; }
        # setup aptitude first
        install_pkg aptitude
        _install_pkg() { sudo aptitude install -q -y "$@"; }
        ;;
    'mac')
        check_pkg() { brew list -1 | grep -q "^${1}\$"; }
        _install_pkg() { brew install "$@"; }
        update_pkg_list() { :; }
        if ! brew help >/dev/null; then
            ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        fi
        ;;
esac

#######################
## install packages on new machine
#######################

packages=()

case $platform in
    'linux')
        # Add Git PPA if not already present
        if ! find /etc/apt/sources.list.d/ -name 'git-core-ubuntu-ppa-*.list'; then
            sudo add-apt-repository -y ppa:git-core/ppa
        fi

        # Define Linux-specific packages
        packages+=(
            # shell tools
            hstr
            vim
            wget
            curl
            # Filesystem tools
            cifs-utils
            plocate
            silversearcher-ag
            sshfs
            sshpass
            autofs
            # Services
            openssh-server
            # Shell and system admin tools
            apt-file
            bmon
            htop
            jq
            lnav
            moreutils
            ncdu
            # Development tools
            build-essential
            cmake
            direnv
            exuberant-ctags
            git
            git-delta
            git-lfs
            meld
            shellcheck
            tig
            unzip
            dos2unix
            # Terminal
            fonts-firacode
            terminator
            tmux
            # GUI
            flameshot
            xclip
            # Mint clipboard manager
            gpaste-2
            gir1.2-gpaste-2
        )
        ;;
    'mac')
        # Define macOS-specific packages
        packages+=(
            coreutils
            ctags
            curl
            dos2unix
            git
            python
            wget
        )
        ;;
esac

# Install all packages
install_pkg "${packages[@]}"
