#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
common_lib="$(dirname "$(readlink -f "$0")")/common-lib"
if [[ -f "$common_lib" ]]; then
    # shellcheck source=common-lib
    . "$common_lib"
else
    echo "Cannot find common-lib."
    exit 1
fi

if ! command -v mise >&/dev/null; then
    curl https://mise.run | sh
fi

eval "$("$HOME/.local/bin/mise" activate bash)"
mise settings set experimental true
mise upgrade
