#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
. common-lib

eval "$("$HOME/.local/bin/mise" activate bash)"
mise use --global go@1.23
go install github.com/BurntSushi/toml/cmd/tomlv@master
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.0
go install golang.org/x/tools/cmd/goimports@latest
go install mvdan.cc/sh/v3/cmd/shfmt@latest
