#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
common_lib="$(dirname "$(readlink -f "$0")")/common-lib"
if [[ -f "$common_lib" ]]; then
    # shellcheck source=common-lib
    . "$common_lib"
else
    echo "Cannot find common-lib."
    exit 1
fi

eval "$("$HOME/.local/bin/mise" activate bash)"
mise use --global go@latest
eval "$("$HOME/.local/bin/mise" activate bash)"

packages=(
    'github.com/BurntSushi/toml/cmd/tomlv@master'
    'github.com/golangci/golangci-lint/cmd/golangci-lint@latest'
    'golang.org/x/tools/cmd/goimports@latest'
    'mvdan.cc/sh/v3/cmd/shfmt@latest'
    'github.com/nao1215/gup@latest'
    'github.com/mikefarah/yq/v4@latest'
    'github.com/google/yamlfmt/cmd/yamlfmt@latest'
    'github.com/ericchiang/pup@latest'
)

for pkg in "${packages[@]}"; do
    go install "$pkg"
done
gup update || true
