#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
. common-lib

eval "$("$HOME/.local/bin/mise" activate bash)"

mise use --global python@3.12
mise plugin add poetry

pip install --upgrade pip
if ! command -v pipx &>/dev/null; then
    pip install --user pipx
fi

pip install -U \
    ansible \
    ruff-lsp \
    ruff

mise settings set experimental true
mise use -g \
    pipx:git-up \
    pipx:percol \
    pipx:pre-commit \
    pipx:flameshow
