#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
. common-lib

eval "$("$HOME/.local/bin/mise" activate bash)"

mise use --global python@3.12 python@3.10 python@3.8
mise plugin add poetry

pip install --upgrade pip
if ! command -v pipx &>/dev/null; then
    pip install --user pipx
fi

pip install -U \
    ansible \
    ruff-lsp \
    ruff \
    poetry \
    pipenv

mise settings set experimental true

uv tool install git-up
uv tool install percol
uv tool install pre-commit
uv tool install flameshow
