#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
common_lib="$(dirname "$(readlink -f "$0")")/common-lib"
if [[ -f "$common_lib" ]]; then
    # shellcheck source=common-lib
    . "$common_lib"
else
    echo "Cannot find common-lib."
    exit 1
fi

eval "$("$HOME/.local/bin/mise" activate bash)"

mise use --global python@3.12 python@3.10 python@3.8
mise plugin add poetry
mise settings set experimental true

pip install --upgrade pip
if ! command -v pipx &>/dev/null; then
    pip install --user pipx
fi

tools=(
    percol
    pipenv
    poetry
    ruff
    git-up
    pre-commit
    ansible
    flameshow
    'git+https://github.com/jcppkkk/update-kube-config.git'
)

# shellcheck disable=SC2034
mapfile -t current_tools < <(uv tool list | grep -v "^-" | cut -d" " -f1)

for tool in "${tools[@]}"; do
    if ! array_contains current_tools "$tool"; then
        uv tool install "$tool"
    fi
done
uv tool upgrade --all
