#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
common_lib="$(dirname "$(readlink -f "$0")")/common-lib"
if [[ -f "$common_lib" ]]; then
    # shellcheck source=common-lib
    . "$common_lib"
else
    echo "Cannot find common-lib."
    exit 1
fi

if [[ $(uname) == Linux ]] && command -v flatpak &>/dev/null; then
    flatpak --user override --filesystem=/usr/share/icons:ro
    flatpak install -y org.telegram.desktop
    flatpak install -y app/com.mattermost.Desktop/x86_64/stable
    flatpak install -y com.ticktick.TickTick
fi
