#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
. common-lib

# Require mise python
eval "$("$HOME/.local/bin/mise" activate bash)"

pip install -U powerline-status powerline-gitstatus

# Setup  https://github.com/powerline/fonts
mkdir -p ~/.local/share/fonts/
(
    cd ~/.local/share/fonts/
    if [[ -f PowerlineSymbols.otf ]]; then
        ts_flag=(-z PowerlineSymbols.otf)
    fi
    curl -fL "${ts_flag[@]}" -o PowerlineSymbols.otf https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
)
mkdir -p ~/.config/fontconfig/conf.d/
(
    cd ~/.config/fontconfig/conf.d/
    if [[ -f 10-powerline-symbols.conf ]]; then
        ts_flag=(-z 10-powerline-symbols.conf)
    fi
    curl -fL "${ts_flag[@]}" -o 10-powerline-symbols.conf https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
)

# patch fonts for powerline
fc-cache -vf ~/.local/share/fonts/ ~/.fonts
