#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
common_lib="$(dirname "$(readlink -f "$0")")/common-lib"
if [[ -f "$common_lib" ]]; then
    # shellcheck source=common-lib
    . "$common_lib"
else
    echo "Cannot find common-lib."
    exit 1
fi

if [[ "$platform" == linux ]]; then
    # set moving window to Super+click
    gsettings set org.cinnamon.desktop.wm.preferences mouse-button-modifier '<Super>'
    gsettings set org.gnome.desktop.wm.preferences focus-new-windows 'smart'

    # start fcitx5 on login
    if [[ -f /usr/share/applications/org.fcitx.Fcitx5.desktop ]]; then
        mkdir -p ~/.config/autostart
        ln -sf /usr/share/applications/org.fcitx.Fcitx5.desktop ~/.config/autostart
    fi
    # linuxmint/cinnamon: Option for Alt-Tab switcher to list windows on current monitor only
    FILE_PATH="/usr/share/cinnamon/js/ui/appSwitcher/appSwitcher.js"
    PATCH_FILE="appSwitcher.patch"

    NEW_LINE="windows = windows.filter(w => w.get_monitor() === global.screen.get_current_monitor())"
    if [[ -f "$FILE_PATH" ]]; then
        if grep -qF "$NEW_LINE" "$FILE_PATH"; then
            pass "appSwitcher 修補已經應用，不需要再次插入。"
        else
            if sudo cat "$PATCH_FILE" | sudo patch "$FILE_PATH"; then
                change "appSwitcher 修補已成功應用。"
            else
                fail "appSwitcher 修補應用失敗，請檢查補丁文件和目標文件。"
            fi
        fi
    fi
fi
