#!/bin/bash
target=$(mise exec node@latest -- which oco)
hook_dir=$(dirname "$0")

# in order to trick opencommit, we need to create a symlink ending like .git/hooks/prepare-commit-msg
oco_hook_dir="$hook_dir/oco_hook/.git/hooks"
mkdir -p "$oco_hook_dir"
ln -fs "$target" "$oco_hook_dir/prepare-commit-msg"
mise exec node@latest -- "$oco_hook_dir/prepare-commit-msg" "$@"
